chore(coverage): bump coverage.py to 7.2.7
Currently failing with an error:
```
ImportError: cannot import name 'MappingProxyType' from partially
initialized module 'types' (most likely due to a circular import)
...~pypi__coverage_cp39_x86_64-unknown-linux-gnu/coverage/types.py)
```

Where the `MappingProxyType` actually exists in Python's std lib.