Fix typo in wheel return type
Causes an error when running from latest main:

```
ERROR: An error occurred during the fetch of repository 'my_deps':
   Traceback (most recent call last):
        File "C:/users/liam/_bazel_liam/gbobcgvx/external/rules_python/python/pip_install/pip_repository.bzl", line 195, column 13, in _pip_repository_impl
                fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed:  (Traceback (most recent call last):
  File "C:\users\liam\_bazel_liam\gbobcgvx\external\python3_8_x86_64-pc-windows-msvc\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\users\liam\_bazel_liam\gbobcgvx\external\python3_8_x86_64-pc-windows-msvc\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\users\liam\_bazel_liam\gbobcgvx\external\python3_8_x86_64-pc-windows-msvc\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\users\liam\_bazel_liam\gbobcgvx\external\rules_python\python\pip_install\parse_requirements_to_bzl\__init__.py", line 19, in <module>
    from python.pip_install.extract_wheels.lib import annotation, arguments, bazel
  File "C:\users\liam\_bazel_liam\gbobcgvx\external\rules_python\python\pip_install\extract_wheels\__init__.py", line 15, in <module>
    from python.pip_install.extract_wheels.lib import (
  File "C:\users\liam\_bazel_liam\gbobcgvx\external\rules_python\python\pip_install\extract_wheels\lib\bazel.py", line 9, in <module>
    from python.pip_install.extract_wheels.lib import (
  File "C:\users\liam\_bazel_liam\gbobcgvx\external\rules_python\python\pip_install\extract_wheels\lib\purelib.py", line 6, in <module>
    from python.pip_install.extract_wheels.lib import wheel
  File "C:\users\liam\_bazel_liam\gbobcgvx\external\rules_python\python\pip_install\extract_wheels\lib\wheel.py", line 28, in <module>
    class Wheel:
  File "C:\users\liam\_bazel_liam\gbobcgvx\external\rules_python\python\pip_install\extract_wheels\lib\wheel.py", line 55, in Wheel
    def entry_points(self) -> Dict[str, tuple[str, str]]:
TypeError: 'type' object is not subscriptable
)
```