fix(coverage): bump to latest coverage.py and fix import shadowing (#1249)
Fixes #1196.

Currently the `coverage.py` module does not work if updated to the
latest
version with the following error:
```
ImportError: cannot import name 'MappingProxyType' from partially
initialized module 'types' (most likely due to a circular import)
...~pypi__coverage_cp39_x86_64-unknown-linux-gnu/coverage/types.py)
```

Where the `MappingProxyType` actually exists in Python's std lib. To
fix,
modify sys.path before the first import of coverage.

Summary:
- chore(coverage): bump coverage.py to 7.2.7
- fix(coverage): patch sys.path before importing anything from coverage
- test(coverage): add extra assertions about the module names