chore: Migrate to rules_bazel_integration_test
This patch deletes the old copy of `bazel_integration_test` that we
had vendored into the repo. It's replaced with the maintained
`rules_bazel_integration_test`.

I tried to enable the tests with Bazel 5.4.0, but we have at least one
Bazel 6+-only feature that we make use of in `rules_python`.

    DEBUG: /home/users/phil/.cache/bazel/_bazel_phil/30d461f9383039e65fc400eede879d16/execroot/rules_python/_tmp/b12274e4f3e9a093f0136650955cdf80/_bazel_phil/93e1b72b6c0a666bcd5ccbe6a9bbbd7b/external/rules_python.override/python/repositories.bzl:550:22: WARNING: ignoring register_coverage_tool=True when registering @python_3_9: Bazel 6+ required, got 5.4.0
    ERROR: Traceback (most recent call last):
            File "/home/users/phil/.cache/bazel/_bazel_phil/30d461f9383039e65fc400eede879d16/execroot/rules_python/_tmp/b12274e4f3e9a093f0136650955cdf80/_bazel_phil/93e1b72b6c0a666bcd5ccbe6a9bbbd7b/external/rules_python.override/python/private/bzlmod/python.bzl", line 132, column 57, in _python_impl
                    toolchain_info = _python_register_toolchains(
            File "/home/users/phil/.cache/bazel/_bazel_phil/30d461f9383039e65fc400eede879d16/execroot/rules_python/_tmp/b12274e4f3e9a093f0136650955cdf80/_bazel_phil/93e1b72b6c0a666bcd5ccbe6a9bbbd7b/external/rules_python.override/python/private/bzlmod/python.bzl", line 49, column 31, in _python_register_toolchains
                    python_register_toolchains(
            File "/home/users/phil/.cache/bazel/_bazel_phil/30d461f9383039e65fc400eede879d16/execroot/rules_python/_tmp/b12274e4f3e9a093f0136650955cdf80/_bazel_phil/93e1b72b6c0a666bcd5ccbe6a9bbbd7b/external/rules_python.override/python/repositories.bzl", line 603, column 39, in python_register_toolchains
                    native.register_toolchains("@{toolchain_repo_name}//:{platform}_toolchain".format(
    Error in register_toolchains: The native module can be accessed only from a BUILD thread. Wrap the function in a macro and call it from a BUILD file
    ERROR: error evaluating module extension python in @rules_python.override//python/extensions:python.bzl

So we only test against 6.2.0 for now.